# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cam.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
import time
import serial.tools.list_ports

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(715, 492)
        MainWindow.setMinimumSize(QtCore.QSize(715, 492))
        MainWindow.setMaximumSize(QtCore.QSize(715, 492))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Cam_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 521, 471))
        self.label.setStyleSheet("background-color: rgb(239, 243, 246);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(520, 0, 201, 471))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(36, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Control = QtWidgets.QWidget()
        self.Control.setObjectName("Control")
        self.Start_btt = QtWidgets.QPushButton(self.Control)
        self.Start_btt.setGeometry(QtCore.QRect(20, 50, 141, 51))
        self.Start_btt.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Start_btt.setIcon(icon1)
        self.Start_btt.setIconSize(QtCore.QSize(40, 40))
        self.Start_btt.setDefault(True)
        self.Start_btt.setFlat(False)
        self.Start_btt.setObjectName("Start_btt")
        self.Stop_btt = QtWidgets.QPushButton(self.Control)
        self.Stop_btt.setGeometry(QtCore.QRect(20, 130, 141, 51))
        self.Stop_btt.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Stop_btt.setIcon(icon2)
        self.Stop_btt.setIconSize(QtCore.QSize(40, 40))
        self.Stop_btt.setDefault(True)
        self.Stop_btt.setFlat(False)
        self.Stop_btt.setObjectName("Stop_btt")
        self.Capture_btt = QtWidgets.QPushButton(self.Control)
        self.Capture_btt.setGeometry(QtCore.QRect(20, 210, 141, 51))
        self.Capture_btt.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("capture.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Capture_btt.setIcon(icon3)
        self.Capture_btt.setIconSize(QtCore.QSize(40, 40))
        self.Capture_btt.setAutoDefault(True)
        self.Capture_btt.setDefault(True)
        self.Capture_btt.setFlat(False)
        self.Capture_btt.setObjectName("Capture_btt")
        self.Exits_btt = QtWidgets.QPushButton(self.Control)
        self.Exits_btt.setGeometry(QtCore.QRect(20, 290, 141, 51))
        self.Exits_btt.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Exits.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exits_btt.setIcon(icon4)
        self.Exits_btt.setIconSize(QtCore.QSize(40, 40))
        self.Exits_btt.setDefault(True)
        self.Exits_btt.setFlat(False)
        self.Exits_btt.setObjectName("Exits_btt")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("control.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Control, icon5, "")
        self.Setting = QtWidgets.QWidget()
        self.Setting.setObjectName("Setting")
        self.label_2 = QtWidgets.QLabel(self.Setting)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 91, 41))
        self.label_2.setObjectName("label_2")
        self.toolButton = QtWidgets.QToolButton(self.Setting)
        self.toolButton.setGeometry(QtCore.QRect(120, 60, 41, 21))
        self.toolButton.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton.setAutoRaise(False)
        self.toolButton.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton.setObjectName("toolButton")
        self.label_3 = QtWidgets.QLabel(self.Setting)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 21, 21))
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(self.Setting)
        self.spinBox.setGeometry(QtCore.QRect(40, 120, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_4 = QtWidgets.QLabel(self.Setting)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 47, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.Setting)
        self.lineEdit.setGeometry(QtCore.QRect(70, 190, 113, 20))
        self.lineEdit.setToolTip("name")
        self.lineEdit.setObjectName("lineEdit")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("setting.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Setting, icon6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 21))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon7)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExits = QtWidgets.QAction(MainWindow)
        self.actionExits.setObjectName("actionExits")
        self.actionPara = QtWidgets.QAction(MainWindow)
        self.actionPara.setObjectName("actionPara")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon8)
        self.actionSave.setObjectName("actionSave")
        self.menuFiles.addAction(self.actionOpen)
        self.menuFiles.addAction(self.actionSave)
        self.menuFiles.addAction(self.actionExits)
        self.menuSetting.addAction(self.actionPara)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "App Cam"))
        self.Start_btt.setText(_translate("MainWindow", "     Start  "))
        self.Stop_btt.setText(_translate("MainWindow", "    Stop  "))
        self.Capture_btt.setText(_translate("MainWindow", "    Capture"))
        self.Exits_btt.setText(_translate("MainWindow", "    Exit      "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Control), _translate("MainWindow", "Control"))
        self.label_2.setText(_translate("MainWindow", " Folder save Image"))
        self.toolButton.setText(_translate("MainWindow", "....."))
        self.label_3.setText(_translate("MainWindow", "Fps"))
        self.label_4.setText(_translate("MainWindow", "File name"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "      image/anything"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Setting), _translate("MainWindow", "Setting"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExits.setText(_translate("MainWindow", "Exits"))
        self.actionPara.setText(_translate("MainWindow", "Para"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionSave.setText(_translate("MainWindow", "Save"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

