# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'requestKey.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lience(object):
    def setupUi(self, Lience):
        Lience.setObjectName("Lience")
        Lience.resize(451, 262)
        Lience.setMinimumSize(QtCore.QSize(451, 262))
        Lience.setMaximumSize(QtCore.QSize(451, 262))
        self.gridLayout = QtWidgets.QGridLayout(Lience)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(Lience)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 1, 1, 1)
        self.label = QtWidgets.QLabel(Lience)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Lience)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                   "")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Lience)
        self.label_4.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 2, 1)
        self.submitButton = QtWidgets.QPushButton(Lience)
        self.submitButton.setStyleSheet("\n"
                                        "\n"
                                        "\n"
                                        "        QPushButton::hover {\n"
                                        "          background-color:#A0A0A0;\n"
                                        "        }\n"
                                        "\n"
                                        "        QPushButton::pressed {\n"
                                        "          background-color: white;\n"
                                        "        }\n"
                                        "\n"
                                        "\n"
                                        "\n"
                                        "\n"
                                        "")
        self.submitButton.setObjectName("submitButton")
        self.gridLayout.addWidget(self.submitButton, 2, 2, 1, 1)
        self.pushButton_sendemail = QtWidgets.QPushButton(Lience)
        self.pushButton_sendemail.setStyleSheet("\n"
                                                "\n"
                                                "\n"
                                                "        QPushButton::hover {\n"
                                                "          background-color:#A0A0A0;\n"
                                                "        }\n"
                                                "\n"
                                                "        QPushButton::pressed {\n"
                                                "          background-color: white;\n"
                                                "        }\n"
                                                "\n"
                                                "\n"
                                                "\n"
                                                "\n"
                                                "")
        self.pushButton_sendemail.setObjectName("pushButton_sendemail")
        self.gridLayout.addWidget(self.pushButton_sendemail, 8, 2, 1, 1)
        self.lineEdit_email = QtWidgets.QLineEdit(Lience)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.gridLayout.addWidget(self.lineEdit_email, 7, 2, 1, 3)
        self.RequestKey = QtWidgets.QPushButton(Lience)
        self.RequestKey.setStyleSheet("        QPushButton::hover {\n"
                                      "          background-color:#A0A0A0;\n"
                                      "        }\n"
                                      "\n"
                                      "        QPushButton::pressed {\n"
                                      "          background-color: white;\n"
                                      "        }")
        self.RequestKey.setObjectName("RequestKey")
        self.gridLayout.addWidget(self.RequestKey, 2, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.usernameLineEdit = QtWidgets.QLineEdit(Lience)
        self.usernameLineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.gridLayout.addWidget(self.usernameLineEdit, 0, 2, 1, 3)
        self.logTextEdit = QtWidgets.QTextEdit(Lience)
        self.logTextEdit.setObjectName("logTextEdit")
        self.gridLayout.addWidget(self.logTextEdit, 3, 2, 1, 3)
        self.passwordLineEdit = QtWidgets.QLineEdit(Lience)
        self.passwordLineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.passwordLineEdit.setInputMask("")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 1, 2, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 5, 1, 1)
        self.label_message = QtWidgets.QLabel(Lience)
        self.label_message.setEnabled(True)
        self.label_message.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                         "color: rgb(255, 0, 0);")
        self.label_message.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_message.setObjectName("label_message")
        self.gridLayout.addWidget(self.label_message, 9, 0, 1, 6)
        self.label_3 = QtWidgets.QLabel(Lience)
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)

        self.retranslateUi(Lience)
        QtCore.QMetaObject.connectSlotsByName(Lience)

    def retranslateUi(self, Lience):
        _translate = QtCore.QCoreApplication.translate
        Lience.setWindowTitle(_translate("Lience", "Lience"))
        self.label_5.setText(_translate("Lience",
                                        "<html><head/><body><p><span style=\" font-weight:500;\">Your Email</span></p></body></html>"))
        self.label.setText(_translate("Lience",
                                      "<html><head/><body><p><span style=\" font-weight:500;\">User Name</span></p></body></html>"))
        self.label_2.setText(_translate("Lience",
                                        "<html><head/><body><p><span style=\" font-weight:500;\">Password</span></p></body></html>"))
        self.label_4.setText(_translate("Lience",
                                        "<html><head/><body><p><span style=\" font-weight:500;\">Key</span></p></body></html>"))
        self.submitButton.setText(_translate("Lience", " Login"))
        self.pushButton_sendemail.setText(_translate("Lience", "Send Message"))
        self.RequestKey.setText(_translate("Lience", "Request key"))
        self.label_3.setText(_translate("Lience", "Try Again!"))
        self.label_message.setText(
            _translate("Lience", "Please check your email.We will contact you as soon as possible."))
        self.pushButton_sendemail.hide()
        self.label_message.hide()
        self.lineEdit_email.hide()
        self.label_5.hide()
        self.label_3.hide()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Lience = QtWidgets.QDialog()
    ui = Ui_Lience()
    ui.setupUi(Lience)
    Lience.show()
    sys.exit(app.exec_())
