# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindown-customCopy.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1181, 613)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icon-Mainwindown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(60, 63, 65);\n"
                                 "font: 8pt \"Segoe UI\";\n"
                                 "color:white;\n"
                                 "\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_camera1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_camera1.sizePolicy().hasHeightForWidth())
        self.pushButton_camera1.setSizePolicy(sizePolicy)
        self.pushButton_camera1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_camera1.setStyleSheet("        QPushButton {\n"
                                              "\n"
                                              "          border-top:0px;\n"
                                              "          border-right:0px;\n"
                                              "           border-bottom:1px solid rgb(102, 104, 104);\n"
                                              "             background-color:rgb(54, 88, 128);\n"
                                              "\n"
                                              "        }\n"
                                              "\n"
                                              "\n"
                                              "\n"
                                              "        QPushButton::hover {\n"
                                              "          background-color:rgb(54, 88, 128);\n"
                                              "           border-top: 2px solid #3C3F41;\n"
                                              "            border-right: 1px solid #3C3F41;\n"
                                              "            border-left: 1px solid #3C3F41;\n"
                                              "          border-radius:5px;\n"
                                              "        }\n"
                                              "\n"
                                              "        QPushButton::pressed {\n"
                                              "          background-color: white;\n"
                                              "        }\n"
                                              "\n"
                                              "        QPushButton::checked {\n"
                                              "          background-color: #D64566;\n"
                                              "        }\n"
                                              "\n"
                                              "         QToolTip {\n"
                                              "          color: white;\n"
                                              "          background-color: rgb(62, 67, 76);\n"
                                              "          border: 0px;\n"
                                              "          }\n"
                                              "\n"
                                              "\n"
                                              "")
        self.pushButton_camera1.setIconSize(QtCore.QSize(40, 30))
        self.pushButton_camera1.setCheckable(True)
        self.pushButton_camera1.setChecked(False)
        self.pushButton_camera1.setAutoDefault(False)
        self.pushButton_camera1.setFlat(True)
        self.pushButton_camera1.setObjectName("pushButton_camera1")
        self.horizontalLayout_9.addWidget(self.pushButton_camera1)
        self.pushButton_auto_manual = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_auto_manual.sizePolicy().hasHeightForWidth())
        self.pushButton_auto_manual.setSizePolicy(sizePolicy)
        self.pushButton_auto_manual.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_auto_manual.setStyleSheet("\n"
                                                  "        QPushButton {\n"
                                                  "               border-right:0px;\n"
                                                  "             border-left:0px;\n"
                                                  "             border-top:0px;\n"
                                                  "               border-bottom:1px solid rgb(102, 104, 104);\n"
                                                  " background-color:rgb(54, 88, 128);\n"
                                                  "        }\n"
                                                  "        QPushButton::hover {\n"
                                                  "              background-color:rgb(54, 88, 128);\n"
                                                  "              border-top: 2px solid #3C3F41;\n"
                                                  "            border-right: 1px solid #3C3F41;\n"
                                                  "            border-left: 1px solid #3C3F41;\n"
                                                  "              border-radius:5px;\n"
                                                  "        }\n"
                                                  "\n"
                                                  "        QPushButton::pressed {\n"
                                                  "          background-color: white;\n"
                                                  "        }\n"
                                                  "        QPushButton::checked {\n"
                                                  "          background-color: #D64566;\n"
                                                  "        }\n"
                                                  "\n"
                                                  "         QToolTip {\n"
                                                  "          color: white;\n"
                                                  "          background-color: rgb(62, 67, 76);\n"
                                                  "          border: 0px;\n"
                                                  "          }")
        self.pushButton_auto_manual.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_auto_manual.setCheckable(True)
        self.pushButton_auto_manual.setChecked(True)
        self.pushButton_auto_manual.setFlat(True)
        self.pushButton_auto_manual.setObjectName("pushButton_auto_manual")
        self.horizontalLayout_9.addWidget(self.pushButton_auto_manual)
        self.pushButton_connectArduino = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_connectArduino.sizePolicy().hasHeightForWidth())
        self.pushButton_connectArduino.setSizePolicy(sizePolicy)
        self.pushButton_connectArduino.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_connectArduino.setStyleSheet("\n"
                                                     "        QPushButton {\n"
                                                     "               border-right:0px;\n"
                                                     "             border-left:0px;\n"
                                                     "             border-top:0px;\n"
                                                     "               border-bottom:1px solid rgb(102, 104, 104);\n"
                                                     "            background-color:rgb(54, 88, 128);\n"
                                                     "        }\n"
                                                     "        QPushButton::hover {\n"
                                                     "              background-color:rgb(54, 88, 128);\n"
                                                     "              border-top: 2px solid #3C3F41;\n"
                                                     "            border-right: 1px solid #3C3F41;\n"
                                                     "            border-left: 1px solid #3C3F41;\n"
                                                     "              border-radius:5px;\n"
                                                     "        }\n"
                                                     "\n"
                                                     "        QPushButton::pressed {\n"
                                                     "          background-color: white;\n"
                                                     "        }\n"
                                                     "        QPushButton::checked {\n"
                                                     "          background-color: #D64566;\n"
                                                     "        }\n"
                                                     "\n"
                                                     "         QToolTip {\n"
                                                     "          color: white;\n"
                                                     "          background-color: rgb(62, 67, 76);\n"
                                                     "          border: 0px;\n"
                                                     "          }")
        self.pushButton_connectArduino.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_connectArduino.setCheckable(True)
        self.pushButton_connectArduino.setChecked(True)
        self.pushButton_connectArduino.setFlat(True)
        self.pushButton_connectArduino.setObjectName("pushButton_connectArduino")
        self.horizontalLayout_9.addWidget(self.pushButton_connectArduino)
        self.pushButton_ClearAll = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ClearAll.sizePolicy().hasHeightForWidth())
        self.pushButton_ClearAll.setSizePolicy(sizePolicy)
        self.pushButton_ClearAll.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_ClearAll.setStyleSheet("        QPushButton {\n"
                                               "            border-top:0px;\n"
                                               "            border-left:0px;\n"
                                               "           border-bottom:1px solid rgb(102, 104, 104);\n"
                                               "            background-color:rgb(54, 88, 128);\n"
                                               "\n"
                                               "        }\n"
                                               "        QPushButton::hover {\n"
                                               "          background-color:rgb(54, 88, 128);\n"
                                               "              border-top: 2px solid #3C3F41;\n"
                                               "            border-right: 1px solid #3C3F41;\n"
                                               "            border-left: 1px solid #3C3F41;\n"
                                               "          border-radius:5px;\n"
                                               "        }\n"
                                               "\n"
                                               "        QPushButton::pressed {\n"
                                               "          background-color: white;\n"
                                               "        }\n"
                                               "\n"
                                               "         QToolTip {\n"
                                               "          color: white;\n"
                                               "          background-color: rgb(62, 67, 76);\n"
                                               "          border: 0px;\n"
                                               "          }")
        self.pushButton_ClearAll.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_ClearAll.setChecked(False)
        self.pushButton_ClearAll.setFlat(True)
        self.pushButton_ClearAll.setObjectName("pushButton_ClearAll")
        self.horizontalLayout_9.addWidget(self.pushButton_ClearAll)
        self.pushButton_test = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_test.sizePolicy().hasHeightForWidth())
        self.pushButton_test.setSizePolicy(sizePolicy)
        self.pushButton_test.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_test.setStyleSheet("\n"
                                           "        QPushButton {\n"
                                           "               border-right:0px;\n"
                                           "             border-left:0px;\n"
                                           "             border-top:0px;\n"
                                           "               border-bottom:1px solid rgb(102, 104, 104);\n"
                                           "           border-right:1px solid rgb(102, 104, 104);\n"
                                           "            background-color:rgb(54, 88, 128);\n"
                                           "        }\n"
                                           "        QPushButton::hover {\n"
                                           "              background-color:rgb(54, 88, 128);\n"
                                           "              border-top: 2px solid #3C3F41;\n"
                                           "            border-right: 1px solid #3C3F41;\n"
                                           "            border-left: 1px solid #3C3F41;\n"
                                           "              border-radius:5px;\n"
                                           "        }\n"
                                           "\n"
                                           "        QPushButton::pressed {\n"
                                           "          background-color: white;\n"
                                           "        }\n"
                                           "\n"
                                           "         QToolTip {\n"
                                           "          color: white;\n"
                                           "          background-color: rgb(62, 67, 76);\n"
                                           "          border: 0px;\n"
                                           "          }")
        self.pushButton_test.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_test.setCheckable(False)
        self.pushButton_test.setChecked(False)
        self.pushButton_test.setFlat(True)
        self.pushButton_test.setObjectName("pushButton_test")
        self.horizontalLayout_9.addWidget(self.pushButton_test)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.horizontalLayout_9.setStretch(2, 1)
        self.horizontalLayout_9.setStretch(3, 1)
        self.horizontalLayout_9.setStretch(4, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.verticalLayout_9.setStretch(0, 6)
        self.verticalLayout_3.addLayout(self.verticalLayout_9)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        self.label_14.setStyleSheet("font: 600 8pt \"Segoe UI\";\n"
                                    "border-right:1px solid rgb(102, 104, 104);")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_22.addWidget(self.label_14)
        self.horizontalLayout_22.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_22)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_File = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_File.sizePolicy().hasHeightForWidth())
        self.label_File.setSizePolicy(sizePolicy)
        self.label_File.setStyleSheet("font: 13pt \"Segoe UI\";\n"
                                      "border-bottom:1px solid rgb(102, 104, 104);\n"
                                      "border-right:1px solid rgb(102, 104, 104);\n"
                                      "")
        self.label_File.setAlignment(QtCore.Qt.AlignCenter)
        self.label_File.setObjectName("label_File")
        self.verticalLayout_6.addWidget(self.label_File)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setStyleSheet("font: 600 8pt \"Segoe UI\";\n"
                                   "border-right:1px solid rgb(102, 104, 104);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        self.horizontalLayout_13.setStretch(0, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_OK_NG_Final = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_OK_NG_Final.sizePolicy().hasHeightForWidth())
        self.label_OK_NG_Final.setSizePolicy(sizePolicy)
        self.label_OK_NG_Final.setStyleSheet("font: 20pt \"Segoe UI\";\n"
                                             "border-bottom:1px solid rgb(102, 104, 104);\n"
                                             "border-right:1px solid rgb(102, 104, 104);\n"
                                             "")
        self.label_OK_NG_Final.setAlignment(QtCore.Qt.AlignCenter)
        self.label_OK_NG_Final.setObjectName("label_OK_NG_Final")
        self.horizontalLayout_14.addWidget(self.label_OK_NG_Final)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.setStretch(2, 6)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setStyleSheet("font: 600 8pt \"Segoe UI\";\n"
                                   "border-right:1px solid rgb(102, 104, 104);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_15.addWidget(self.label_9)
        self.horizontalLayout_15.setStretch(0, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_quantity_Total = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_quantity_Total.sizePolicy().hasHeightForWidth())
        self.label_quantity_Total.setSizePolicy(sizePolicy)
        self.label_quantity_Total.setStyleSheet("font: 20pt \"Segoe UI\";\n"
                                                "border-bottom:1px solid rgb(102, 104, 104);\n"
                                                "")
        self.label_quantity_Total.setAlignment(QtCore.Qt.AlignCenter)
        self.label_quantity_Total.setObjectName("label_quantity_Total")
        self.horizontalLayout_7.addWidget(self.label_quantity_Total)
        self.label_result_QuantityTotal = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_QuantityTotal.sizePolicy().hasHeightForWidth())
        self.label_result_QuantityTotal.setSizePolicy(sizePolicy)
        self.label_result_QuantityTotal.setStyleSheet("font: 24pt \"Segoe UI\";\n"
                                                      "border-bottom:1px solid rgb(102, 104, 104);\n"
                                                      "border-right:1px solid rgb(102, 104, 104);\n"
                                                      "")
        self.label_result_QuantityTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result_QuantityTotal.setObjectName("label_result_QuantityTotal")
        self.horizontalLayout_7.addWidget(self.label_result_QuantityTotal)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 6)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        self.label_10.setStyleSheet("font: 600 8pt \"Segoe UI\";\n"
                                    "")
        self.label_10.setIndent(0)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_17.addWidget(self.label_10)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setStyleSheet("border-left:1px solid rgb(102, 104, 104);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_17.addWidget(self.label_21)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_TotalOK = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_TotalOK.sizePolicy().hasHeightForWidth())
        self.label_TotalOK.setSizePolicy(sizePolicy)
        self.label_TotalOK.setStyleSheet("font: 20pt \"Segoe UI\";\n"
                                         "border-bottom:1px solid rgb(102, 104, 104);\n"
                                         "\n"
                                         "")
        self.label_TotalOK.setAlignment(QtCore.Qt.AlignCenter)
        self.label_TotalOK.setObjectName("label_TotalOK")
        self.horizontalLayout_8.addWidget(self.label_TotalOK)
        self.label_resultOK_Total = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_resultOK_Total.sizePolicy().hasHeightForWidth())
        self.label_resultOK_Total.setSizePolicy(sizePolicy)
        self.label_resultOK_Total.setStyleSheet("font: 24pt \"Segoe UI\";\n"
                                                "border-bottom:1px solid rgb(102, 104, 104);\n"
                                                "\n"
                                                "")
        self.label_resultOK_Total.setAlignment(QtCore.Qt.AlignCenter)
        self.label_resultOK_Total.setObjectName("label_resultOK_Total")
        self.horizontalLayout_8.addWidget(self.label_resultOK_Total)
        self.label_totalNG = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_totalNG.sizePolicy().hasHeightForWidth())
        self.label_totalNG.setSizePolicy(sizePolicy)
        self.label_totalNG.setStyleSheet("font: 20pt \"Segoe UI\";\n"
                                         "border-bottom:1px solid rgb(102, 104, 104);\n"
                                         "border-left:1px solid rgb(102, 104, 104);\n"
                                         "color:red;")
        self.label_totalNG.setAlignment(QtCore.Qt.AlignCenter)
        self.label_totalNG.setObjectName("label_totalNG")
        self.horizontalLayout_8.addWidget(self.label_totalNG)
        self.label_resultNG_total = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_resultNG_total.sizePolicy().hasHeightForWidth())
        self.label_resultNG_total.setSizePolicy(sizePolicy)
        self.label_resultNG_total.setStyleSheet("font: 24pt \"Segoe UI\";\n"
                                                "border-bottom:1px solid rgb(102, 104, 104);\n"
                                                "border-right:1px solid rgb(102, 104, 104);\n"
                                                "color:red;\n"
                                                "")
        self.label_resultNG_total.setAlignment(QtCore.Qt.AlignCenter)
        self.label_resultNG_total.setObjectName("label_resultNG_total")
        self.horizontalLayout_8.addWidget(self.label_resultNG_total)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(2, 1)
        self.horizontalLayout_8.setStretch(3, 1)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 6)
        self.verticalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 4)
        self.verticalLayout_3.setStretch(3, 3)
        self.verticalLayout_3.setStretch(4, 3)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_cam1_OK = QtWidgets.QLabel(self.centralwidget)
        self.label_cam1_OK.setMinimumSize(QtCore.QSize(0, 50))
        self.label_cam1_OK.setStyleSheet("font: 20pt \"Segoe UI\";\n"
                                         "border-top:1px solid rgb(102, 104, 104);\n"
                                         "border-left:1px solid rgb(102, 104, 104);\n"
                                         "border-bottom:1px solid rgb(102, 104, 104);")
        self.label_cam1_OK.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam1_OK.setObjectName("label_cam1_OK")
        self.horizontalLayout_3.addWidget(self.label_cam1_OK)
        self.label_ResultOK_Cam1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ResultOK_Cam1.setMinimumSize(QtCore.QSize(0, 20))
        self.label_ResultOK_Cam1.setStyleSheet("font: 20pt \"Segoe UI\";\n"
                                               "border-top:1px solid rgb(102, 104, 104);\n"
                                               "border-right:1px solid rgb(102, 104, 104);\n"
                                               "border-bottom:1px solid rgb(102, 104, 104);")
        self.label_ResultOK_Cam1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ResultOK_Cam1.setObjectName("label_ResultOK_Cam1")
        self.horizontalLayout_3.addWidget(self.label_ResultOK_Cam1)
        self.label_NG_cam1 = QtWidgets.QLabel(self.centralwidget)
        self.label_NG_cam1.setMinimumSize(QtCore.QSize(0, 20))
        self.label_NG_cam1.setStyleSheet("font: 20pt \"Segoe UI\";\n"
                                         "border-top:1px solid rgb(102, 104, 104);\n"
                                         "border-bottom:1px solid rgb(102, 104, 104);\n"
                                         "color:red;")
        self.label_NG_cam1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NG_cam1.setObjectName("label_NG_cam1")
        self.horizontalLayout_3.addWidget(self.label_NG_cam1)
        self.label_ResultNG_cam1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ResultNG_cam1.setMinimumSize(QtCore.QSize(0, 20))
        self.label_ResultNG_cam1.setStyleSheet("font: 20pt \"Segoe UI\";\n"
                                               "border-top:1px solid rgb(102, 104, 104);\n"
                                               "border-right:1px solid rgb(102, 104, 104);\n"
                                               "border-bottom:1px solid rgb(102, 104, 104);\n"
                                               "color:red;")
        self.label_ResultNG_cam1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ResultNG_cam1.setObjectName("label_ResultNG_cam1")
        self.horizontalLayout_3.addWidget(self.label_ResultNG_cam1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_cam2_OK = QtWidgets.QLabel(self.centralwidget)
        self.label_cam2_OK.setStyleSheet("font: 20pt \"Segoe UI\";\n"
                                         "border-top:1px solid rgb(102, 104, 104);\n"
                                         "border-bottom:1px solid rgb(102, 104, 104);")
        self.label_cam2_OK.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam2_OK.setObjectName("label_cam2_OK")
        self.horizontalLayout_5.addWidget(self.label_cam2_OK)
        self.label_ResultOk_cam2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ResultOk_cam2.setStyleSheet("font: 20pt \"Segoe UI\";\n"
                                               "border-top:1px solid rgb(102, 104, 104);\n"
                                               "border-bottom:1px solid rgb(102, 104, 104);\n"
                                               "border-right:1px solid rgb(102, 104, 104);")
        self.label_ResultOk_cam2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ResultOk_cam2.setObjectName("label_ResultOk_cam2")
        self.horizontalLayout_5.addWidget(self.label_ResultOk_cam2)
        self.label_NG_cam2 = QtWidgets.QLabel(self.centralwidget)
        self.label_NG_cam2.setStyleSheet("font: 20pt \"Segoe UI\";\n"
                                         "border-top:1px solid rgb(102, 104, 104);\n"
                                         "border-bottom:1px solid rgb(102, 104, 104);\n"
                                         "color:red;")
        self.label_NG_cam2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NG_cam2.setObjectName("label_NG_cam2")
        self.horizontalLayout_5.addWidget(self.label_NG_cam2)
        self.label_ResultNG_cam2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ResultNG_cam2.setStyleSheet("font: 20pt \"Segoe UI\";\n"
                                               "border-top:1px solid rgb(102, 104, 104);\n"
                                               "border-bottom:1px solid rgb(102, 104, 104);\n"
                                               "border-right:1px solid rgb(102, 104, 104);\n"
                                               "color:red;")
        self.label_ResultNG_cam2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ResultNG_cam2.setObjectName("label_ResultNG_cam2")
        self.horizontalLayout_5.addWidget(self.label_ResultNG_cam2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        self.label_cam2 = QtWidgets.QLabel(self.centralwidget)
        self.label_cam2.setStyleSheet("background-color: #3E434C;\n"
                                      "border-right:1px solid rgb(102, 104, 104);\n"
                                      "border-left:1px solid rgb(102, 104, 104);\n"
                                      "border-bottom:1px solid rgb(102, 104, 104);\n"
                                      "border-top:1px solid rgb(102, 104, 104);")
        self.label_cam2.setText("")
        self.label_cam2.setPixmap(QtGui.QPixmap(":/newPrefix/Cam1-horizontal.png"))
        self.label_cam2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam2.setObjectName("label_cam2")
        self.gridLayout.addWidget(self.label_cam2, 2, 0, 1, 2)
        self.label_cam1 = QtWidgets.QLabel(self.centralwidget)
        self.label_cam1.setStyleSheet("background-color: #3E434C;\n"
                                      "border-right:1px solid rgb(102, 104, 104);\n"
                                      "border-left:1px solid rgb(102, 104, 104);\n"
                                      "border-bottom:1px solid rgb(102, 104, 104);\n"
                                      "border-top:1px solid rgb(102, 104, 104);")
        self.label_cam1.setText("")
        self.label_cam1.setPixmap(QtGui.QPixmap(":/newPrefix/Cam1-horizontal.png"))
        self.label_cam1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam1.setObjectName("label_cam1")
        self.gridLayout.addWidget(self.label_cam1, 0, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_cam1_result1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cam1_result1.sizePolicy().hasHeightForWidth())
        self.label_cam1_result1.setSizePolicy(sizePolicy)
        self.label_cam1_result1.setMinimumSize(QtCore.QSize(0, 20))
        self.label_cam1_result1.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                              "border-left:1px solid rgb(102, 104, 104);\n"
                                              "border-right:1px solid rgb(102, 104, 104);")
        self.label_cam1_result1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam1_result1.setObjectName("label_cam1_result1")
        self.horizontalLayout_4.addWidget(self.label_cam1_result1)
        self.label_cam1_result2 = QtWidgets.QLabel(self.centralwidget)
        self.label_cam1_result2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_cam1_result2.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                              "border-right:1px solid rgb(102, 104, 104);")
        self.label_cam1_result2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam1_result2.setObjectName("label_cam1_result2")
        self.horizontalLayout_4.addWidget(self.label_cam1_result2)
        self.label_cam1_result3 = QtWidgets.QLabel(self.centralwidget)
        self.label_cam1_result3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_cam1_result3.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                              "border-right:1px solid rgb(102, 104, 104);")
        self.label_cam1_result3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam1_result3.setObjectName("label_cam1_result3")
        self.horizontalLayout_4.addWidget(self.label_cam1_result3)
        self.label_cam1_result4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cam1_result4.sizePolicy().hasHeightForWidth())
        self.label_cam1_result4.setSizePolicy(sizePolicy)
        self.label_cam1_result4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_cam1_result4.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                              "border-right:1px solid rgb(102, 104, 104);")
        self.label_cam1_result4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam1_result4.setObjectName("label_cam1_result4")
        self.horizontalLayout_4.addWidget(self.label_cam1_result4)
        self.label_cam1_result5 = QtWidgets.QLabel(self.centralwidget)
        self.label_cam1_result5.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                              "border-right:1px solid rgb(102, 104, 104);")
        self.label_cam1_result5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam1_result5.setObjectName("label_cam1_result5")
        self.horizontalLayout_4.addWidget(self.label_cam1_result5)
        self.label_cam1_result6 = QtWidgets.QLabel(self.centralwidget)
        self.label_cam1_result6.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                              "border-right:1px solid rgb(102, 104, 104);")
        self.label_cam1_result6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam1_result6.setObjectName("label_cam1_result6")
        self.horizontalLayout_4.addWidget(self.label_cam1_result6)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_cam2_result1 = QtWidgets.QLabel(self.centralwidget)
        self.label_cam2_result1.setMinimumSize(QtCore.QSize(0, 20))
        self.label_cam2_result1.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                              "border-right:1px solid rgb(102, 104, 104);\n"
                                              "border-left:1px solid rgb(102, 104, 104);")
        self.label_cam2_result1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam2_result1.setObjectName("label_cam2_result1")
        self.horizontalLayout_2.addWidget(self.label_cam2_result1)
        self.label_cam2_result2 = QtWidgets.QLabel(self.centralwidget)
        self.label_cam2_result2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_cam2_result2.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                              "border-right:1px solid rgb(102, 104, 104);")
        self.label_cam2_result2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam2_result2.setObjectName("label_cam2_result2")
        self.horizontalLayout_2.addWidget(self.label_cam2_result2)
        self.label_cam2_result3 = QtWidgets.QLabel(self.centralwidget)
        self.label_cam2_result3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_cam2_result3.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                              "")
        self.label_cam2_result3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam2_result3.setObjectName("label_cam2_result3")
        self.horizontalLayout_2.addWidget(self.label_cam2_result3)
        self.label_cam2_result4 = QtWidgets.QLabel(self.centralwidget)
        self.label_cam2_result4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_cam2_result4.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                              "border-right:1px solid rgb(102, 104, 104);\n"
                                              "border-left:1px solid rgb(102, 104, 104);")
        self.label_cam2_result4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam2_result4.setObjectName("label_cam2_result4")
        self.horizontalLayout_2.addWidget(self.label_cam2_result4)
        self.label_cam2_result5 = QtWidgets.QLabel(self.centralwidget)
        self.label_cam2_result5.setMinimumSize(QtCore.QSize(0, 20))
        self.label_cam2_result5.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                              "border-right:1px solid rgb(102, 104, 104);")
        self.label_cam2_result5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam2_result5.setObjectName("label_cam2_result5")
        self.horizontalLayout_2.addWidget(self.label_cam2_result5)
        self.label_cam2_result6 = QtWidgets.QLabel(self.centralwidget)
        self.label_cam2_result6.setStyleSheet("font: 10pt \"Segoe UI\";\n"
                                              "border-right:1px solid rgb(102, 104, 104);")
        self.label_cam2_result6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cam2_result6.setObjectName("label_cam2_result6")
        self.horizontalLayout_2.addWidget(self.label_cam2_result6)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 2)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 4)
        self.gridLayout_2.setColumnStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1181, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setMinimumSize(QtCore.QSize(0, 20))
        self.menubar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setStyleSheet("QMenuBar {  \n"
                                   "    font: 10pt \"Segoe UI\";\n"
                                   "    background-color:rgb(60, 63, 65);\n"
                                   "    spacing: 3px; /* spacing between menu bar items */\n"
                                   "}\n"
                                   "\n"
                                   "\n"
                                   "QMenuBar::item {\n"
                                   "    padding: 5px 8px;\n"
                                   "    background: transparent;\n"
                                   "    border-radius: 0px;\n"
                                   "}\n"
                                   "\n"
                                   "QMenuBar::item::hover {\n"
                                   "    background: #4B6EAF;\n"
                                   "}\n"
                                   "\n"
                                   "QMenuBar::item:selected { /* when selected using mouse or keyboard */\n"
                                   "    background: #4B6EAF;\n"
                                   "}\n"
                                   "\n"
                                   "QMenuBar::item:pressed {\n"
                                   "    background: #4B6EAF;\n"
                                   "}\n"
                                   "\n"
                                   "QMenu {\n"
                                   "    font: 10pt \"Segoe UI\";\n"
                                   "    padding: 0px 0px  0px  0px;\n"
                                   "    background-color: #3C3F41;   \n"
                                   "    border:1px solid rgb(102, 104, 104);\n"
                                   "    margin: 0px;\n"
                                   "}\n"
                                   "QMenu::item {\n"
                                   "    background-color: transparent;\n"
                                   "}\n"
                                   "QMenu::item:selected{ \n"
                                   "    background-color: #4B6EAF;\n"
                                   "}\n"
                                   "")
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setAutoFillBackground(False)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionCamera1 = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCamera1.setIcon(icon1)
        self.actionCamera1.setVisible(True)
        self.actionCamera1.setPriority(QtWidgets.QAction.NormalPriority)
        self.actionCamera1.setObjectName("actionCamera1")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionExits = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/exits.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExits.setIcon(icon3)
        self.actionExits.setObjectName("actionExits")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/About.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDocumment = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumment.setIcon(icon5)
        self.actionDocumment.setObjectName("actionDocumment")
        self.actionArduino_Uno = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/Ard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionArduino_Uno.setIcon(icon6)
        self.actionArduino_Uno.setObjectName("actionArduino_Uno")
        self.actionCamera_2 = QtWidgets.QAction(MainWindow)
        self.actionCamera_2.setIcon(icon1)
        self.actionCamera_2.setObjectName("actionCamera_2")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExits)
        self.menuSetting.addAction(self.actionCamera1)
        self.menuSetting.addAction(self.actionArduino_Uno)
        self.menuSetting.addAction(self.actionCamera_2)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionDocumment)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.label_ntfCam1 = QtWidgets.QLabel(self.label_cam1)
        self.label_ntfCam1.raise_()
        self.label_ntfCam1.setStyleSheet("font: 600 8pt \"Segoe UI\";\n"
                                         "border-left:1px solid rgb(102, 104, 104);\n"
                                         "border-bottom:1px solid rgb(102, 104, 104);\n"
                                         "border-right:0px;\n"
                                         "background-color:transparent;")
        self.label_ntfCam1.setObjectName("label_11")
        self.label_ntfCam1.setText("Notify Cam1")
        self.label_ntfCam1.setAlignment(QtCore.Qt.AlignCenter)

        self.label_ntfCam2 = QtWidgets.QLabel(self.label_cam2)
        self.label_ntfCam2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ntfCam2.raise_()
        self.label_ntfCam2.setStyleSheet("font: 600 8pt \"Segoe UI\";\n"
                                         "border-left:1px solid rgb(102, 104, 104);\n"
                                         "border-bottom:1px solid rgb(102, 104, 104);\n"
                                         "border-right:0px;\n"
                                         "background-color:transparent;")
        self.label_ntfCam2.setObjectName("label_11")
        self.label_ntfCam2.setText("Notify Cam2")
        self.retranslateUi(MainWindow)
        MainWindow.sizeChanged.connect(self.moveLabel)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def moveLabel(self):
        self.label_ntfCam1.setGeometry(self.label_cam1.size().width() * 0.8, 0,
                                       self.label_cam1.size().width() * 0.2, 30)
        self.label_ntfCam2.setGeometry(self.label_cam2.size().width() * 0.8, 0,
                                       self.label_cam2.size().width() * 0.2, 30)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CamArd"))
        self.pushButton_camera1.setToolTip(_translate("MainWindow", "Start Camera 1"))
        self.pushButton_camera1.setText(_translate("MainWindow", "Cam"))
        self.pushButton_auto_manual.setToolTip(_translate("MainWindow", "Auto / Manual"))
        self.pushButton_auto_manual.setText(_translate("MainWindow", "Auto"))
        self.pushButton_connectArduino.setToolTip(_translate("MainWindow", "Start Serial "))
        self.pushButton_connectArduino.setText(_translate("MainWindow", "Serial"))
        self.pushButton_ClearAll.setToolTip(_translate("MainWindow", "Clear Quantity"))
        self.pushButton_ClearAll.setText(_translate("MainWindow", "Clear"))
        self.pushButton_test.setToolTip(_translate("MainWindow", "Test "))
        self.pushButton_test.setText(_translate("MainWindow", "Test"))
        self.label_14.setText(_translate("MainWindow", "File"))
        self.label_File.setText(_translate("MainWindow", "No File"))
        self.label_8.setText(_translate("MainWindow", "Result "))
        self.label_OK_NG_Final.setText(_translate("MainWindow", "OK"))
        self.label_9.setText(_translate("MainWindow", "Quantity"))
        self.label_quantity_Total.setText(_translate("MainWindow", "Quantity"))
        self.label_result_QuantityTotal.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "NG/OK"))
        self.label_TotalOK.setText(_translate("MainWindow", "OK"))
        self.label_resultOK_Total.setText(_translate("MainWindow", "0"))
        self.label_totalNG.setText(_translate("MainWindow", "NG"))
        self.label_resultNG_total.setText(_translate("MainWindow", "0"))
        self.label_cam1_OK.setText(_translate("MainWindow", "OK"))
        self.label_ResultOK_Cam1.setText(_translate("MainWindow", "0"))
        self.label_NG_cam1.setText(_translate("MainWindow", "NG"))
        self.label_ResultNG_cam1.setText(_translate("MainWindow", "0"))
        self.label_cam2_OK.setText(_translate("MainWindow", "OK"))
        self.label_ResultOk_cam2.setText(_translate("MainWindow", "0"))
        self.label_NG_cam2.setText(_translate("MainWindow", "NG"))
        self.label_ResultNG_cam2.setText(_translate("MainWindow", "0"))
        self.label_cam1_result1.setText(_translate("MainWindow", "Result1"))
        self.label_cam1_result2.setText(_translate("MainWindow", "Result2"))
        self.label_cam1_result3.setText(_translate("MainWindow", "Result3"))
        self.label_cam1_result4.setText(_translate("MainWindow", "Result4"))
        self.label_cam1_result5.setText(_translate("MainWindow", "Result5"))
        self.label_cam1_result6.setText(_translate("MainWindow", "Result6"))
        self.label_cam2_result1.setText(_translate("MainWindow", "Result1"))
        self.label_cam2_result2.setText(_translate("MainWindow", "Result2"))
        self.label_cam2_result3.setText(_translate("MainWindow", "Result3"))
        self.label_cam2_result4.setText(_translate("MainWindow", "Result4"))
        self.label_cam2_result5.setText(_translate("MainWindow", "Result5"))
        self.label_cam2_result6.setText(_translate("MainWindow", "Result6"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionCamera1.setText(_translate("MainWindow", "Camera 1"))
        self.actionCamera1.setShortcut(_translate("MainWindow", "Ctrl+Shift+P"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExits.setText(_translate("MainWindow", "Exits"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionDocumment.setText(_translate("MainWindow", "Documment"))
        self.actionArduino_Uno.setText(_translate("MainWindow", "Arduino Uno"))
        self.actionArduino_Uno.setShortcut(_translate("MainWindow", "Ctrl+Shift+A"))
        self.actionCamera_2.setText(_translate("MainWindow", "Camera 2"))
        self.actionCamera_2.setShortcut(_translate("MainWindow", "Ctrl+Shift+U"))


# import tampro_rc


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
